// <auto-generated />
namespace Estoque_WPF_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BancodeDadosCriado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BancodeDadosCriado));
        
        string IMigrationMetadata.Id
        {
            get { return "202010151607074_Banco de Dados Criado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
